---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
    fabric8.io/iconUrl: "img/icons/camel.svg"
    fabric8.io/git-commit: "378a6bf0664ee5c9cae32cb77d65bfb284246d4a"
    fabric8.io/git-branch: "master"
  labels:
    expose: "true"
    provider: "fabric8"
    project: "demo-soap"
    version: "1.0.0-SNAPSHOT"
    group: "org.jboss.fis2.demo"
  name: "demo-soap"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "demo-soap"
    provider: "fabric8"
    group: "org.jboss.fis2.demo"
  type: "LoadBalancer"
