spec:
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.2"
              memory: 512Mi
            limits:
              cpu: "1.0"
              memory: 512Mi
          env:
          - name: SPRING_DSFIS2_URL
            value: jdbc:postgresql://postgresql:5432/fis2demo